import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import TanstackProvider from "@/providers/TanstackProvider"
import { Toaster } from "@/components/ui/sonner"

const lombok = localFont({
  src: "../../assets/fonts/loominaire-regular.ttf",
  variable: "--font-lombok",
})

const sans = Open_Sans({
  weight: ["300", "400", "500"],
  variable: "--font-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lombok.variable} ${sans.variable} dark font-sans`}>
        <TanstackProvider>{children}</TanstackProvider>
        <Toaster richColors className="z-50" />
      </body>
    </html>
  )
}
