import type { Metadata } from "next";
import { Open_Sans, Bebas_Neue } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import { Toaster } from "@/components/ui/sonner";

const lombok = localFont({
  src: "../../assets/fonts/loominaire-regular.ttf",
  variable: "--font-lombok",
  display: "block",
});

const sans = Open_Sans({
  weight: ["300", "400", "500"],
  variable: "--font-sans",
  subsets: ["latin"],
  display: "block",
});

const bebas = Bebas_Neue({
  weight: ["400"],
  variable: "--font-bebas",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={`${lombok.variable} ${sans.variable} ${bebas.variable} dark font-sans`}
      lang="en"
    >
      <body>
        <TanstackProvider>{children}</TanstackProvider>
        <Toaster richColors className="z-50" />
      </body>
    </html>
  );
}
